source "https://rubygems.org"

gem "jekyll", "~> 3.6.3"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem 'jekyll-mentions'
gem 'jekyll-feed'
gem 'jekyll-paginate'

gem "github-pages", "~> 203", group: :jekyll_plugins

